version: '3.8'

services:
  postgres:
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Remove init scripts in production - use migrations instead
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5  # More secure for production

  backend:
    restart: unless-stopped
    environment:
      NODE_ENV: production
    volumes: []  # Remove volume mounts in production
    command: npm start  # Use production start command

  # Production frontend (served by nginx)
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro  # SSL certificates
    depends_on:
      - backend

volumes:
  postgres_data:
    driver: local

networks:
  wcw-network:
    driver: bridge